// An error is randomly returned to demonstrate how the error is propagated
// to the 'onError' function when an error occurs in the 'onTrigger'
// function. Therefore position of the error might differ and can be appeared in random order.
$ ballerina run task_timer.bal
Timer task demo
Cleaning up...
1
Cleaning up...
2
Cleaning up...
3
Cleaning up...
4
Cleaning up...
5
[ERROR] cleanup failed{message:"Cleanup error", cause:null}
Cleaning up...
6
Cleaning up...
....
....
....
